### ISSUE TITLE
А клиент новый будите делать с вэб интерфейсом или еще что нить свежое..

### ISSUE THREAD

**Issue by dcbeelinekz2** [DCNF/Hublist#5]
которое толкнет DC++ уже вперед, а не старый вид в котором он есть
Хочется чтоб DC жило и переродилось в что то новое...

**Comment by dcbeelinekz2** [comment]
Расширение в Хром, бота в телеграмм, что нить в этом роде, интересно - развивающее , новый прорыт толчок будет ваше в этом протоколе?

**Comment by dennwc** [comment]
Этот вопрос конечно мало относится к хаблисту (этот репозиторий о нем), но я всё равно отвечу здесь

Веб-клиент пока не планируется, т.к. уже существует [AirDC++ Web](https://airdcpp-web.github.io/) и [EiskaltDC++ Web](https://github.com/eiskaltdcpp/eiskaltdcpp-web).

По поводу протокола - да, конечно, есть много планов по улучшению и мы будем их внедрять поочередно. Вот здесь можно будет следить за изменениями протокола: [direct-connect/protocol](https://github.com/direct-connect/protocol).
